version: '3'
services:
  web:
    build: ./dockerfile/web
    ports:
      - "3000:3000"
    volumes:
      - .:/FinCrawler
    depends_on:
      - db
      - mail
    tty: true
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  db:
    image: harisekhon/hbase:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  mail:
    image: tozd/postfix:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
