FROM ruby:2.2.5

RUN gem install nokogiri -no-ri -no-rdoc
RUN gem install hbaserb -no-ri -no-rdoc
#RUN gem install hbase_thrift_ruby -no-ri -no-rdoc
RUN gem install hashie -no-ri -no-rdoc
RUN gem install mail -no-ri -no-rdoc